plugin/vcgn:Remove local defined ip4_interface_first_address
Function ip4_interface_first_address has been defined in
vnet/ip/ip4.h, and result an compile issue.

  CC       vcgn/cnat_ipv4_icmp_error_outside_input.lo
  CC       vcgn/cnat_logging.lo
vcgn/cnat_logging.c:361:1: error: conflicting types for 'ip4_interface_first_address'
 ip4_interface_first_address (ip4_main_t * im, u32 sw_if_index)
 ^
In file included from /usr/include/vnet/ip/ip.h:57:0,
                 from vcgn/cnat_logging.c:24:
/usr/include/vnet/ip/ip4.h:390:1: note: previous declaration of 'ip4_interface_first_address' was here
 ip4_interface_first_address (ip4_main_t * im, u32 sw_if_index,
 ^
make: *** [vcgn/cnat_logging.lo] Error 1

Change-Id: I1165c9bb778263c195ed34ab438dcb27dfd207bc
Signed-off-by: Michael Qiu <qiudayu@chinac.com>